### ISSUE TITLE
Possible bug in Processing bold tags inside lists

### ISSUE THREAD

**Issue by JayJayBinks** [markdom/java-markdom#2]
Version: 0.0.4

When Commonmark with a Bold tag inside a List is processed, some text is lost.
Following test case demonstrates the bug.

```
@Test
    void should_export_list_and_bold_markdown_as_html() {
      String text = "1. List **item** with bold text\n"
        + "2. List item without bold text";
      Parser parser = Parser.builder().build();
      Document commonMarkDoc = (Document) parser.parse(text);

      MarkdomFactory factory = new BasicMarkdomFactory();
      MarkdomDocument markdomDocument = new AtlassianCommonmarkDocumentMarkdomDispatcher(commonMarkDoc).handle(
        new MarkdomDocumentMarkdomHandler(factory));

      String htmlSnippet = markdomDocument.handle(new JsoupHtmlDocumentMarkdomHandler()).asElementsText(true);
      assertNotNull(htmlSnippet);
      assertThat(htmlSnippet)
        .isEqualTo("<ol start=\"1\">\n"
          + "<li>List <strong>item</strong> with bold text</li>\n"
          + "<li>List item without bold text</li>\n"
          + "</ol>");
    }
```

**Comment by toKrause** [comment]
I'll look into it.

**Comment by toKrause** [comment]
The current implementation of `JsoupHtmlDocumentMarkdomHandler` will indeed remove all previously added node when a text node is added to an element, so only the most recently added text node survives. Caused by erroneously calling `Element#text(String)` instead of `Element#appendText(String)`.

Will be [fixed](https://github.com/markdom/java-markdom/commit/1033b7d2b65c9c1c21bb9364f70bcfc34bfbc372) with the next release.
